### PR TITLE
#185 Update Linux install script to refer to the correct relative paths

### LINKED ISSUE #185: Linux install script not working due to wrong reference to `./fonts` instead of `../fonts` etc
After the macos and linux installation scripts were moved to `utils` the linux installation script was not updated to refer to the correct relative path.

### PR DESCRIPTION
**Pull request by brunofin**
Modify script so it works with the instructions provided in README.

Closes #185

### CODE REVIEW

**Review by barnett-yuxiang — COMMENTED** [review]
Have you tested it?

**Comment by brunofin** [comment]
@barnett-yuxiang yes. When I originally wrote the linux install scripts, the instructions I provided in the README.md file were considering running the script from the root of the repository: https://github.com/githubnext/monaspace/pull/29/commits/29880d58671f6d1e28370d27dca04364cb8b48e7

Since then, it seems the instructions for both Mac and Linux have changed to first `cd` into the `utils` folder and run the script from there. Whoever did those changes also changed the mac os install script to refer to the parent path with `..` but did not update the linux install scripts. That's what this PR is doing.

**Comment by Finii** [comment]
There are multiple PRs that fix the same thing. Ever looked through open PRs?

For example
* #64

**Comment by idan** [comment]
Fixed in the batch of commits around 93c4bcdb772fe34c4aef415a87e1521ae9947012

**Pull request closed without merging**
