### PR TITLE
Make install script executable

### PR DESCRIPTION
**Pull request by omgjlk**
Without it being executable the install instructions fail.

`sudo: ./util/install_macos.sh: command not found`

### CODE REVIEW

**Comment by prplecake** [comment]
The instructions don't use sudo...

https://github.com/githubnext/monaspace/blob/421b5a8975c3d74f080a855802a05177a0fc1225/README.md?plain=1#L51

**Comment by omgjlk** [comment]
Fair points. 

I will argue though that by having a #!  as a first line of the file including the interpreter to use, the install directions can be simplified to just `./util/install_macos.sh`, assuming that the file is executable, which appears to be the intent.

**Comment by idan** [comment]
Fixed in 8847e6c809aae8afac2ea9e137850fe870862421

**Comment by idan** [comment]
Thank you for the PR, it's appreciated! Was fixed while I was doing a pass on the installation issues, this is not a rejection 💞

**Pull request closed without merging**
