### PR TITLE
Add documentation block for using homebrew

### LINKED ISSUE #14: Distribution on Homebrew?
Thanks a lot for making this font, and I can't wait to try it out! 🎉

However, I believe you would make it even easier for macOS users to install (and upgrade) your font via a [`brew cask`](https://docs.brew.sh/Cask-Cookbook) instead of using a shell script. You can do this either by adding it to https://github.com/Homebrew/homebrew-cask-fonts, or by making a tap of your own including that cask. 🙇

### PR DESCRIPTION
**Pull request by mheob**
Add a documentation block for installing the font via [homebrew](https://brew.sh/) on a MacOS.

Addition to and closes #14

### CODE REVIEW

**Comment by altaywtf** [comment]
shouldn't we do `brew tap homebrew/cask-fonts` first?

```bash
brew install --cask font-monaspace
brew install font-monaspace
```

worked out for me, but `brew install --cask font-monaspace` didn't.

**Comment by mheob** [comment]
You are right. Since I had already tapped `homebrew/cask-fonts`, I forgot that we have to call it at least once.

I added it now.

**Comment by krehel** [comment]
Thanks for adding the instruction for Homebrew!

**Comment by idan** [comment]
Thank you!!

**Pull request merged**
