### PR TITLE
 fixed install_linux.sh file

### PR DESCRIPTION
**Pull request by satyamvatsal**
now font can be installed from the util directory.

### CODE REVIEW

**Review by antonkesy — APPROVED** [review]
LGTM

**Comment by satyamvatsal** [comment]
I am new to this repo and GitHub
Can you use full form of LGTM

**Review by barnett-yuxiang — COMMENTED** [review]
Is it not good to use the project root path?

**Comment by satyamvatsal** [comment]
But most of the people run the script by cd into the repository.
So I think it will be more sensible.

**Comment by idan** [comment]
Fixed in the batch of commits around 93c4bcdb772fe34c4aef415a87e1521ae9947012

**Pull request closed without merging**
